### ISSUE TITLE
Upcoming change of PHP version

### ISSUE THREAD

**Issue by ssddanbrown** [turnkeylinux-apps/bookstack#1]
Hello :wave: 
I'm Dan, the creator/lead-dev of BookStack.

Just wanted to warn about an upcoming change to the minimum supported PHP version for BookStack.
It'll be changing from php7.4 to php8.0 in the next feature release (Likely due end of the month).
Thought I'd raise that here as I'm not exactly sure how PHP versions are managed for turnkey, and I couldn't immediately see a specific PHP version in use from the sources here.

**Comment by JedMeister** [comment]
Thanks so much @ssddanbrown!

FWIW, we actually have a [consolidated issue tracker](https://github.com/turnkeylinux/tracker/issues/) (and it looks like I forgot to disable issues on this repo - whoops). But no harm done. I'll open an issue over there and cross post this. I'll leave this here for now, but once it's resolved I'll disable issues in this repo (which will hide this issue too IIRC).

Anyway, we're based on Debian stable, so only have PHP 7.4 as default currently (as you may be aware, Debian testing will have 8.2 by the time it becomes stable - sometime later this year).

Thanks for the heads up. I'll rebuild the BookStack appliance with newer PHP (probably 8.1 - installed from deb.sury.org) and the current version of Bookstack. That will make life easier for BookStack users to maintain their servers. As you're possibly aware, it's not that hard to upgrade PHP but our user base tend to not be seasoned Linux users, so the easier it is, the better.

Take care and thanks again for the heads up.

**Comment by ssddanbrown** [comment]
@JedMeister Thanks, that all sounds good! I'll therefore close this off since you've opened this via your consolidated tracker, and I'll keep that issue location in mind for an future messages.

**Comment by JedMeister** [comment]
Thanks @ssddanbrown - I'll disable issues here now. Thanks again.
